services:
  fastapi:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ows@123
      MYSQL_DATABASE: test_db
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  volumes:
    mysql_data: